### ISSUE TITLE
Need a few options setting

### ISSUE THREAD

**Issue by kaceo** [kurrestahlberg/turndown-vscode#6]
Nice VSC extension here, exactly what I was looking for!  But compared to the website demo at https://domchristie.github.io/turndown/ there are fewer configuration settings, e.g. heading style, horizontal rule, etc.  Please do put them into the next release?

**Comment by kurrestahlberg** [comment]
Hi. I don't really maintain this extension. I needed it for one task but that need is gone. 

Feel free to fork and take over!
